version: "3"

working_directory: /app

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      -run:
        name: Install docker-compose
        command: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and run the Docker Compose project
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: Run the tests
          command: |
            docker-compose run web npm test
