version: "3"

working_directory: /app

jobs:
  build:
    docker:
      - image: docker/compose:1.29.2
    steps:
      - checkout
      - run:
          name: Build and run the Docker Compose project
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: Run the tests
          command: |
            docker-compose run web npm test
